name: Actions test

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  setup-tektoncd:
    runs-on: ubuntu-24.04
    steps:
      # using KinD to provide the Kubernetes instance and kubectl
      # - uses: helm/kind-action@v1.5.0
      #   with:
      #     cluster_name: kind

      # setting up Tekton Pipelines, CLI and additional components...
      - uses: AlanGreene/tektoncd-actions/setup-tektoncd@main
        with:
          pipeline_version: latest
          setup_registry: "true"
          patch_etc_hosts: "true"
